# Generated by Django 5.1 on 2025-02-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('profile_pic', models.ImageField(upload_to='doc_pics')),
                ('username', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('profile_pic', models.ImageField(upload_to='doc_pics')),
                ('username', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('pincode', models.IntegerField()),
            ],
        ),
    ]
