# Generated by Django 5.1 on 2025-03-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_blogs_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=30)),
                ('pat_name', models.CharField(max_length=30)),
                ('spec', models.CharField(max_length=30)),
                ('book_date', models.DateField()),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='spec',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
