# Generated by Django 5.1 on 2025-03-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_booking_doctor_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.CharField(max_length=20),
        ),
    ]
